#include "mainUI.h"

void GLAPIENTRY MessageCallback( GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar* message, const void* userParam ) {
    if(type == GL_DEBUG_TYPE_ERROR){
        std::cerr << "GL ERROR: " << message << std::endl; 
    } else {
        std::cout << "LOG: " << message << std::endl;
    }
}

int mainUI(){
    /* Initialize the library */
    if (!glfwInit())
        return 1;

    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    /* Create a windowed mode window and its OpenGL context */
    GLFWwindow* window = glfwCreateWindow(WINDOW_WIDTH, WINDOW_HEIGHT, "Tesi OpenGL", NULL, NULL);
    if (!window)
    {
        glfwTerminate();
        return 2;
    }

    /* Make the window's context current */
    glfwMakeContextCurrent(window);

    if(!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)){
        glfwTerminate();
        return 3;
    }
    glEnable(GL_DEBUG_OUTPUT);
    glDebugMessageCallback(MessageCallback, 0);

    //Init ImGui
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO();
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;
    io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
    ImGui_ImplGlfw_InitForOpenGL(window, true);
    ImGui_ImplOpenGL3_Init();

    UI ui;
    Raytracer raytracer;
    Settings* defaultSettings = ui.getSettings();
    raytracer.update(defaultSettings->resolution[0], defaultSettings->resolution[1]);

    Viewport viewport;

    //Get maximum work group count
    int workGroupMax[3];
    glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_COUNT, 0, &workGroupMax[0]);
    glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_COUNT, 1, &workGroupMax[1]);
    glGetIntegeri_v(GL_MAX_COMPUTE_WORK_GROUP_COUNT, 2, &workGroupMax[2]);

    //Buffer
    GLuint transmissionBuffer;
    glGenBuffers(1, &transmissionBuffer);
    glBindBuffer(GL_SHADER_STORAGE_BUFFER, transmissionBuffer);

    std::vector<Planet> planets;
    std::ifstream inputFile(UNIVERSE);
    if(inputFile.is_open()){
        deserializeAll(inputFile, &(raytracer.camera), &(raytracer.background), &planets);
        inputFile.close();
    }

    std::vector<PlanetGLSL> converted = planetsToGLSL(&planets);
    glBufferData(GL_SHADER_STORAGE_BUFFER, converted.size() * sizeof(PlanetGLSL), converted.data(), GL_STATIC_READ);
    glBindBufferBase(GL_SHADER_STORAGE_BUFFER, 1, transmissionBuffer);

    //Framebuffer
    Framebuffer framebuffer;
    framebuffer.update(WINDOW_WIDTH, WINDOW_HEIGHT);

    //Uniform stuff for the manual render

    while (!glfwWindowShouldClose(window)) {
        glfwPollEvents();

        //---Renderer---
        Settings* settings = ui.getSettings();
        if(ui.dispatch.getState()){
            int w = settings->resolution[0];
            int h = settings->resolution[1];
            raytracer.update(w, h);
            raytracer.dispatch(w, h);
            ui.dispatch.clear();
        }

        if(ui.updateUniverse.getState()){
            std::vector<PlanetGLSL> converted = planetsToGLSL(&planets);
            glBindBuffer(GL_SHADER_STORAGE_BUFFER, transmissionBuffer);
            glBufferData(GL_SHADER_STORAGE_BUFFER, converted.size() * sizeof(PlanetGLSL), converted.data(), GL_STATIC_READ);
            ui.updateUniverse.clear();
        }

        if(ui.saveUniverse.getState()){
            std::ofstream output(UNIVERSE);
            serializeAll(output, &(raytracer.camera), &(raytracer.background), &planets);
            output.close();
        }
    
        glMemoryBarrier(GL_SHADER_IMAGE_ACCESS_BARRIER_BIT);
        if(ui.exportImage.getState()){
            //Get string of file to save to (autogenerated)
            std::ostringstream filename;
            auto t = std::time(nullptr);
            filename << std::put_time(std::localtime(&t), "output_%d-%m-%Y_%H-%M-%S.png");
            //Get texture data
            int w = settings->resolution[0];
            int h = settings->resolution[1];
            std::vector<unsigned char> output (w * h * 3); //rgb
            glBindTexture(GL_TEXTURE_2D, raytracer.getOutputTexture());
            glGetTexImage(GL_TEXTURE_2D, 0, GL_RGB, GL_UNSIGNED_BYTE, &output[0]);
            stbi_write_png(filename.str().c_str(), w, h, 3, output.data(), w * 3);
            std::cout << "Saved to " << filename.str() << std::endl;
            ui.exportImage.clear();
        }

        //---From compute shader output to framebuffer---
        framebuffer.bind();
        glClearColor(0,0,0,1);
        glClear(GL_COLOR_BUFFER_BIT);
        viewport.update(settings, raytracer.getOutputTexture());
        viewport.draw();
        framebuffer.unbind();
      
        //---UI---
        ui.begin();
        //ImGui::ShowDemoWindow(); 
        ui.settings();
        ui.universe(&(raytracer.camera), &(raytracer.background), &planets);
        ui.viewport(framebuffer.getColorTexture());
        ui.end();

        glfwSwapBuffers(window);
    }

    glfwTerminate();
    return 0;
}
